### ISSUE TITLE
Domain Setup: nft.chrypnotoad.com

### ISSUE THREAD

**Issue by TheErebusAI** [TheErebusAI/chrypnotoad-nft#1]
**Assigned to: @chrypnotoad**

Setup required in Squarespace for domain configuration:

1. Log into Squarespace
2. Go to Settings > Domains
3. Add custom subdomain:
   - Create CNAME record for "nft"
   - Point to: theerebusai.github.io
   - TTL: 3600 (or default)

Note: Site will be live at https://theerebusai.github.io/chrypnotoad-nft/

After DNS setup, the site will automatically work with nft.chrypnotoad.com

**Comment by chrypnotoad** [comment]
- Added CNAME nft to  theerebusai.github.io in squarespace. It does take me to github but I see a 404. 
- changed the repo to public since github pages are not allowed in private repos without enterprise
- enabled pages in repo settings @TheErebusAI you may want to check the deploy settings on that
